require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SmsNotificationsController do

  # This should return the minimal set of attributes required to create a valid
  # SmsNotification. As you add validations to SmsNotification, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "receiver_user_id" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SmsNotificationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sms_notifications as @sms_notifications" do
      sms_notification = SmsNotification.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sms_notifications).should eq([sms_notification])
    end
  end

  describe "GET show" do
    it "assigns the requested sms_notification as @sms_notification" do
      sms_notification = SmsNotification.create! valid_attributes
      get :show, {:id => sms_notification.to_param}, valid_session
      assigns(:sms_notification).should eq(sms_notification)
    end
  end

  describe "GET new" do
    it "assigns a new sms_notification as @sms_notification" do
      get :new, {}, valid_session
      assigns(:sms_notification).should be_a_new(SmsNotification)
    end
  end

  describe "GET edit" do
    it "assigns the requested sms_notification as @sms_notification" do
      sms_notification = SmsNotification.create! valid_attributes
      get :edit, {:id => sms_notification.to_param}, valid_session
      assigns(:sms_notification).should eq(sms_notification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SmsNotification" do
        expect {
          post :create, {:sms_notification => valid_attributes}, valid_session
        }.to change(SmsNotification, :count).by(1)
      end

      it "assigns a newly created sms_notification as @sms_notification" do
        post :create, {:sms_notification => valid_attributes}, valid_session
        assigns(:sms_notification).should be_a(SmsNotification)
        assigns(:sms_notification).should be_persisted
      end

      it "redirects to the created sms_notification" do
        post :create, {:sms_notification => valid_attributes}, valid_session
        response.should redirect_to(SmsNotification.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sms_notification as @sms_notification" do
        # Trigger the behavior that occurs when invalid params are submitted
        SmsNotification.any_instance.stub(:save).and_return(false)
        post :create, {:sms_notification => { "receiver_user_id" => "invalid value" }}, valid_session
        assigns(:sms_notification).should be_a_new(SmsNotification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SmsNotification.any_instance.stub(:save).and_return(false)
        post :create, {:sms_notification => { "receiver_user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sms_notification" do
        sms_notification = SmsNotification.create! valid_attributes
        # Assuming there are no other sms_notifications in the database, this
        # specifies that the SmsNotification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SmsNotification.any_instance.should_receive(:update).with({ "receiver_user_id" => "MyString" })
        put :update, {:id => sms_notification.to_param, :sms_notification => { "receiver_user_id" => "MyString" }}, valid_session
      end

      it "assigns the requested sms_notification as @sms_notification" do
        sms_notification = SmsNotification.create! valid_attributes
        put :update, {:id => sms_notification.to_param, :sms_notification => valid_attributes}, valid_session
        assigns(:sms_notification).should eq(sms_notification)
      end

      it "redirects to the sms_notification" do
        sms_notification = SmsNotification.create! valid_attributes
        put :update, {:id => sms_notification.to_param, :sms_notification => valid_attributes}, valid_session
        response.should redirect_to(sms_notification)
      end
    end

    describe "with invalid params" do
      it "assigns the sms_notification as @sms_notification" do
        sms_notification = SmsNotification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SmsNotification.any_instance.stub(:save).and_return(false)
        put :update, {:id => sms_notification.to_param, :sms_notification => { "receiver_user_id" => "invalid value" }}, valid_session
        assigns(:sms_notification).should eq(sms_notification)
      end

      it "re-renders the 'edit' template" do
        sms_notification = SmsNotification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SmsNotification.any_instance.stub(:save).and_return(false)
        put :update, {:id => sms_notification.to_param, :sms_notification => { "receiver_user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sms_notification" do
      sms_notification = SmsNotification.create! valid_attributes
      expect {
        delete :destroy, {:id => sms_notification.to_param}, valid_session
      }.to change(SmsNotification, :count).by(-1)
    end

    it "redirects to the sms_notifications list" do
      sms_notification = SmsNotification.create! valid_attributes
      delete :destroy, {:id => sms_notification.to_param}, valid_session
      response.should redirect_to(sms_notifications_url)
    end
  end

end
