// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build beta1)

public class Invoke_API implements java.io.Serializable {
    protected java.lang.String string_1;
    protected java.lang.String string_2;
    protected WsParamSet wsParamSet_3;
    
    public Invoke_API() {
    }
    
    public Invoke_API(java.lang.String string_1, java.lang.String string_2, WsParamSet wsParamSet_3) {
        this.string_1 = string_1;
        this.string_2 = string_2;
        this.wsParamSet_3 = wsParamSet_3;
    }
    
    public java.lang.String getString_1() {
        return string_1;
    }
    
    public void setString_1(java.lang.String string_1) {
        this.string_1 = string_1;
    }
    
    public java.lang.String getString_2() {
        return string_2;
    }
    
    public void setString_2(java.lang.String string_2) {
        this.string_2 = string_2;
    }
    
    public WsParamSet getWsParamSet_3() {
        return wsParamSet_3;
    }
    
    public void setWsParamSet_3(WsParamSet wsParamSet_3) {
        this.wsParamSet_3 = wsParamSet_3;
    }
}
