// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build beta1)


public class Invoke_APIResponse implements java.io.Serializable {
    protected WsParamSet result;
    
    public Invoke_APIResponse() {
    }
    
    public Invoke_APIResponse(WsParamSet result) {
        this.result = result;
    }
    
    public WsParamSet getResult() {
        return result;
    }
    
    public void setResult(WsParamSet result) {
        this.result = result;
    }
}
