// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build beta1)

public interface IWebService extends java.rmi.Remote {
    public WsParamSet invoke_API(java.lang.String string_1, java.lang.String string_2, WsParamSet wsParamSet_3) throws 
         java.rmi.RemoteException;
}
