// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build beta1)

import javax.xml.rpc.*;

public interface WebService extends javax.xml.rpc.Service {
    public IWebService getIWebServicePort() throws javax.xml.rpc.ServiceException;
}
