// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build beta1)


public class WsParam implements java.io.Serializable {
    protected java.lang.String value;
    protected java.lang.String name;
    
    public WsParam() {
    }
    
    public WsParam(java.lang.String value, java.lang.String name) {
        this.value = value;
        this.name = name;
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public void setValue(java.lang.String value) {
        this.value = value;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
}
