// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (10.1.3.0.0, build beta1)


public class WsParamSet implements java.io.Serializable {
    protected WsParam[] param;
    
    public WsParamSet() {
    }
    
    public WsParamSet(WsParam[] param) {
        this.param = param;
    }
    
    public WsParam[] getParam() {
        return param;
    }
    
    public void setParam(WsParam[] param) {
        this.param = param;
    }
}
